kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: cardano-sl-prod
spec:
  replicas: 1
  template:
    metadata:
      name: api
      labels:
        app: cardano-sl
        role: backend
        env: production
    spec:
      containers:
      - name: cardano-sl
        image: khwhahn/cardano-sl:0.1
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
