kind: Service
apiVersion: v1
metadata:
  name: cardano-sl
spec:
  selector:
    app: cardano-sl
    role: backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
