apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: cardano-tls
  name: cardano-tls
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
status: {}
