apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yaml convert
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: null
  labels:
    io.kompose.service: cardano-sl
  name: cardano-sl
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cardano-sl
    spec:
      containers:
      - image: khwhahn/cardano-sl:0.1
        name: cardano-sl
        resources: {}
        volumeMounts:
        - mountPath: /home/cardano/cardano-sl/state-wallet-mainnet
          name: cardano-sl-claim0
        - mountPath: /home/cardano/cardano-sl/state-wallet-mainnet/tls
          name: cardano-tls
      restartPolicy: Always
      volumes:
      - name: cardano-sl-claim0
        persistentVolumeClaim:
          claimName: cardano-sl-claim0
      - name: cardano-tls
        persistentVolumeClaim:
          claimName: cardano-tls
status: {}
