apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: daedalus-claim0
  name: daedalus-claim0
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
status: {}
