apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yaml convert
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: null
  labels:
    io.kompose.service: daedalus
  name: daedalus
spec:
  type: NodePort
  ports:
  - name: vnc
    port: 5901
    targetPort: 5901
    protocol: TCP
  - name: http
    port: 6901
    targetPort: 6901
    protocol: TCP
  selector:
    io.kompose.service: daedalus
status:
  loadBalancer: {}
