version: '3'

services:
  cardano-sl:
    build: ../cardano-sl
    volumes:
      - ~/.cardano:/home/cardano/cardano-sl/state-wallet-mainnet
      - cardano_tls:/home/cardano/cardano-sl/state-wallet-mainnet/tls

  daedalus:
    depends_on:
      - cardano-sl
    build: ../daedalus
    network_mode: "service:cardano-sl"
    environment:
      DISPLAY: "$DISPLAY"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - cardano_tls:/home/daedalus/daedalus/tls

volumes:
  cardano_tls:
