kind: Service
apiVersion: v1
metadata:
  name: daedalus
spec:
  selector:
    app: daedalus
    role: frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
